### ISSUE TITLE
composer install error 

### ISSUE THREAD

**Issue by wangxiaodong1021** [urre/wordpress-nginx-docker-compose#10]
When I run `docker-compose run composer install`, there is an error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.1 but your PHP version (7.0.7) does not satisfy that requirement.
```

I try to change https://github.com/urre/wordpress-nginx-docker-compose/blob/ed3b77eac9824a072c408386a07e7b7fdc154f5f/src/composer.json#L37 
to `"php": "^7.0"`to fix this error.

#https://github.com/composer/composer/issues/5480

**Comment by urre** [comment]
@wangxiaodong1021 thanks! i've pushed [a fix for this now](https://github.com/urre/wordpress-nginx-docker-compose/commit/4d77e4456085a0c1ec8d768478ce17c06b2df2ed)
