### ISSUE TITLE
Unable to upload media

### ISSUE THREAD

**Issue by mkenacnibuk** [urre/wordpress-nginx-docker-compose#104]
Hi, what I learned up to know is BEDROCK is fine - separates wordpress structure away ( the "wp" dir below on screeenshot ) and have all well organized, etc. etc..
![image](https://user-images.githubusercontent.com/17276604/209568777-a9d2fcdd-c719-4a54-b326-f330cc4e5f6a.png)

Today I put some new themes into composer, nothing else and started playing with dockerized wordpress.

All is running well, except one think - I can't upload png/jpg/media files. Each time I try a I see warning

![Screenshot from 2022-12-26 17-42-18](https://user-images.githubusercontent.com/17276604/209568972-ecfbb9bf-2b71-4845-b50f-eef66b5b3430.png)
![Screenshot from 2022-12-26 17-40-31](https://user-images.githubusercontent.com/17276604/209568974-75aa78e8-7626-4b78-96fc-b839cd8f6496.png)

The warning message is telling me: **Unable to create directory wp-content/uploads/2022/09. Is its parent directory writable by the**

...the **wp-content** seems to me the path to **pure** not **bedrock** wordpress structure

I will try to find out solution/fix, but maybe smbd of you know the right place to correct some php definition already.

What I tried already is

- check insterested folders' permissions - all seems to me to be ok
- edit src/web/wp-config.php
- nothing helped :-(
![image](https://user-images.githubusercontent.com/17276604/209570071-148903ea-6973-4ac7-93cd-bf63ac0d6e31.png)

-----
OS system info:
![image](https://user-images.githubusercontent.com/17276604/209570343-2c3077e4-035e-42d9-b2b6-5c2f532be13a.png)

**Comment by mkubincanek** [comment]
FYI: Hmm funny, I woke up, ran ```docker-compose``` as ```sudo```. Media were uploaded successfully, stopped docker, ran docker as common os user and media were still uploaded successfully.

Both positive results **without** the the line mentioned yesterday in wp-config.php
![image](https://user-images.githubusercontent.com/95072164/209645935-2ecb0153-d712-4837-8f0c-285fef42ec4d.png)

**Comment by urre** [comment]
I can upload media without issues without changing anything, and without running with `sudo`, so I don't think this is anything wrong with this repo.
