### ISSUE TITLE
Site Working very slow

### ISSUE THREAD

**Issue by ohadkorenok** [urre/wordpress-nginx-docker-compose#105]
Hey how are you? I'm working on Macosx m1 and i have a very good computer but for some reason this site is very slow. Do you know why?
Would it change in production or this is the performance of the website? (3-6s for rendering)?
Do you know maybe what can be related to it? 
Can the nginx proxy maybe slow everything down?

how can i optimize it? 
Thank you!

**Comment by urre** [comment]
Hey, yea I have the same issues actually, also on M1 now. It's the Docker images not tuned for ARM. Will look into it

**Comment by urre** [comment]
I've addresses this now. You should try it again.
