### ISSUE TITLE
Mailhog not working

### ISSUE THREAD

**Issue by adamddurrant** [urre/wordpress-nginx-docker-compose#108]
Error response from daemon: Invalid container name (-mailhog), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by urre** [comment]
What `APP_NAME` have you set in your `.env`? Default in `/.env.example` is `myapp`. So the mailhog container get the name `myapp-mailhog`

**Comment by urre** [comment]
```
myapp-mailhog     | 2023/04/30 11:17:42 Using in-memory storage
myapp-mailhog     | 2023/04/30 11:17:42 [SMTP] Binding to address: 0.0.0.0:1025
myapp-mailhog     | [HTTP] Binding to address: 0.0.0.0:8025
myapp-mailhog     | 2023/04/30 11:17:42 Serving under http://0.0.0.0:8025/
```

and then you run it 

![CleanShot 2023-04-30 at 13 20 30@2x](https://user-images.githubusercontent.com/307676/235350224-5eebc455-d75e-44f0-937b-4611832e90cb.jpg)

**Comment by urre** [comment]
did you get this to work @adamddurrant ?
