### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by SimplifyAll** [urre/wordpress-nginx-docker-compose#24]
Hi!
Thanks for sharing your work — it's a truly amazing, and well-designed template
but also quite a complex one.
Unfortunately, I've run into some trouble during the setup...
I'm running Ubuntu. I've done everything from the `Readme.md`, but finally got:

```
Warning: Packets out of order. Expected 0 received 1. Packet size=69 in
/var/www/html/web/wp/wp-includes/wp-db.php on line 1633
Warning: mysqli_real_connect(): MySQL server has gone away in 
/var/www/html/web/wp/wp-includes/wp-db.php on line 1633
Warning:  mysqli_real_connect(): Error while reading greeting packet. PID=6 in 
/var/www/html/web/wp/wp-includes/wp-db.php on line 1633
Warning:  mysqli_real_connect(): (HY000/2006): MySQL server has gone away in 
/var/www/html/web/wp/wp-includes/wp-db.php on line 1633

MySQL server has gone away
```
phpMyAdmin is reachable, but when trying to log in, the same errors pop up.
Would you mind helping me to find out what's going on?

**Comment by urre** [comment]
@SimplifyAll Hey! I've never seen this happen in this setup. I'm using macOS. Maybe we need to tweak the mysql settings file for Linux?

**Comment by urre** [comment]
@SimplifyAll did you test more on Linux?

**Comment by SimplifyAll** [comment]
Hi!
Firstly, thanks for your response @urre. 
Unfortunately, I didn't find out what's going on but found another way to run WP locally. So maybe in the future, I'll try to solve this issue.

**Comment by trenccan777** [comment]
I had a similar problem using Windows 10 and virtual machine. This [bedrock setup](https://github.com/trenccan777/WP-Bedrock-Docker-setup) is running good for me.

**Comment by wavehamza** [comment]
Hello @urre  I'm facing the same issue on MAC as well so weird !! 

After using Urre repo for 3 or 4 times now showing me the erreur.

`Warning: Packets out of order. Expected 0 received 1. Packet size=69 in /var/www/html/web/wp/wp-includes/wp-db.php on line 1653 Warning: mysqli_real_connect(): Error while reading greeting packet. PID=8 in /var/www/html/web/wp/wp-includes/wp-db.php on line 1653 Warning: mysqli_real_connect(): (HY000/2006): MySQL server has gone away in /var/www/html/web/wp/wp-includes/wp-db.php on line 1653
`
