### ISSUE TITLE
Error Loading extension section SAN

### ISSUE THREAD

**Issue by TLaw763** [urre/wordpress-nginx-docker-compose#26]
Hi, I downloaded the code earlier today when I tried to run the create-cert.sh file in VS Code on macOS, I get the following error...

Error Loading extension section SAN
4492713580:error:22FFF06D:X509 V3 routines:func(4095):invalid null value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/x509v3/v3_utl.c:355:
4492713580:error:22FFF069:X509 V3 routines:func(4095):invalid extension string:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/x509v3/v3_conf.c:149:name=subjectAltName,section=DNS:
4492713580:error:22FFF080:X509 V3 routines:func(4095):error in extension:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/x509v3/v3_conf.c:100:name=subjectAltName, value=DNS:

**Comment by urre** [comment]
@TLaw763 Hi, do you have openssl installed from home brew? Do you run the script using `./create-cert.sh` or `bash create-cert.sh`

**Comment by TLaw763** [comment]
Sorry, I restarted my laptop and ran ./create-cert.sh again and it worked.
I not sure why it didn't work straight after installing Openssh...

Thanks for the help though

**Comment by urre** [comment]
Great!
