### ISSUE TITLE
./create-cert.sh Nothing happens. Why ?

### ISSUE THREAD

**Issue by AionQRy** [urre/wordpress-nginx-docker-compose#27]
All Command in Cli folders.
![nothappen](https://user-images.githubusercontent.com/28930273/76135607-f3b0e100-605a-11ea-8d4f-623973722277.jpg)

Not Respond. Not happens in command line.
I'm running in windown 10.
Do you have an answer for me? Thank You

**Comment by urre** [comment]
@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

**Comment by AionQRy** [comment]
Thank for you reply.Yes  i got it.I have installed this one.https://www.openssl.org/This is true openssl?เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

**Comment by AionQRy** [comment]
I think it does not support windows.Do you think that's right?เมื่อ 11 มี.ค. 2020 10:47 anacuse15@hotmail.com เขียนว่าThank for you reply.Yes  i got it.I have installed this one.https://www.openssl.org/This is true openssl?เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

เมื่อ 11 มี.ค. 2020 04:29 Urban Sandén <notifications@github.com> เขียนว่า@AionQRy Hi, I haven't tested this on a Windows system. Do you have openSSL installed?

**Comment by styssi** [comment]
Not working in Windows. Just created a Pull Requests with a batch script that works in windows.

**Comment by urre** [comment]
@AionQRy there is windows support now.
