### ISSUE TITLE
Persist DB

### ISSUE THREAD

**Issue by membla** [urre/wordpress-nginx-docker-compose#3]
Lovely – super clean and well documented.

I would’ve assumed there to be a volume for db persistence per default too though, no?

**Comment by urre** [comment]
Thanks!

Yea, i can add that!

**Comment by urre** [comment]
@membla I've now added this! (https://github.com/urre/wordpress-nginx-docker-compose/commit/67bd93e7bf33e9ba5b1741a1f2c66c5621803c04)
