### ISSUE TITLE
create-cert.sh not portable to CentOS/RHEL

### ISSUE THREAD

**Issue by stunney** [urre/wordpress-nginx-docker-compose#32]
An error is produced when running create-cert.sh on CentOS (7.7):

> [vagrant@localhost cli]$ ./create-cert.sh
> cat: /etc/ssl/openssl.cnf: No such file or directory
> Generating a 2048 bit RSA private key
> 
> writing new private key to 192.168.1.193.key
> 
> unable to find 'distinguished_name' in config
> problems making Certificate Request
> 140288227555216:error:0E06D06C:configuration file routines:NCONF_get_string:no value:conf_lib.c:324:group=req name=distinguished_name

OpenSSL.conf is installed in /etc/pki/tls/openssl.cnf by default and is not found in your script.

Not a big deal, would be helpful to add this to the capabilities of your super-handy template!

**Comment by stunney** [comment]
trust-cert.sh has a similar compatibility issue.  Trying to place certificates into the incorrect location:
This code snippet by @adessoAG can help update the script:
https://gist.github.com/kekru/deabd57f0605ed95d5c8246d18483687

**Comment by urre** [comment]
@stunney Can you create a PR?

**Comment by urre** [comment]
I've switched to mkcert now which supports Linux better.
