### ISSUE TITLE
APP_NAME variable not set

### ISSUE THREAD

**Issue by gaisho** [urre/wordpress-nginx-docker-compose#33]
hello, 

When I run docker-compose up -d, I get the following warning: 
WARNING: The APP_NAME variable is not set. Defaulting to a blank string.

Then a number errors appear when trying to create mysql.  

--

Note that I've set the APP_NAME in the .env file. 

Please help, thanks.

**Comment by vusisindane** [comment]
Problem solved.  Just needed to restart the console.
