### ISSUE TITLE
How do I install xdebug with this stack?

### ISSUE THREAD

**Issue by gaisho** [urre/wordpress-nginx-docker-compose#34]
Hello thanks for the container.  

I'm a noob.  Just wanted to know how do I setup xDebug to work with phpstorm and this stack?

**Comment by urre** [comment]
@gaisho hey! you would have to install xDebug in the Container, via the `Dockerfile`. You could mount a volume for the `xdebug.ini` settings also. It's not included in this starter setup right now, but some hints. Closing this issue, but thanks for your question.

**Comment by gaisho** [comment]
Hi, I'm new to Docker, and I'm reading as much as I can.  I've tried several options based on what I can find online.  Nothing seems to be working for me, with this configuration. 

If you can, please point me to the right resource.  Or post an example here.  Thanks.

**Comment by gaisho** [comment]
Just in case anybody has the same issue.  Here's the solution that worked for me.
https://gist.github.com/TSmulkys/ba2920addedc9cc385b1ffa81634b637

**Comment by urre** [comment]
@gaisho 👍

**Comment by mortensassi** [comment]
@gaisho how did you implement it? i don't see a php service in this stack
