### ISSUE TITLE
Wordpress Index.php redirect loop causing performance issues

### ISSUE THREAD

**Issue by gaisho** [urre/wordpress-nginx-docker-compose#36]
Hi Urre, 

Once again, thanks for the great stack.  I thought you should be aware of the multiple index.php redirects from each browser request.  Scroll down to see Docker log.  Also, note that there are no plugins installed in my installation.

The trouble is that when large plugins like WooCommerce and Buddypress are installed, the site takes up to 3min to load.  I suspect it's because of these redirects.  

I also enabled xDebug and realised that the functions.php file is also called 4 or sometimes 6 times.  That means from a single call, WP tries to load several times.

I did a bit of digging and found this discussion on stackexchange:
https://wordpress.stackexchange.com/questions/292322/wordpress-index-php-seems-to-perform-unwanted-redirect-301

I have not been able to make the fix yet, because the wp-config file is really customised.  When I change the .env file, the site falls apart.  Also, this might be caused by the SSL certificate.  Anyway, please have a look at it.

P.S  here's a DOCKER log of all the calls that are initiated from a single browser request

```
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:24:41 +0000 "GET /index.php" 301
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:24:41 +0000 "GET /index.php" 404
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:24:42 +0000 "GET /index.php" 404
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:24:43 +0000 "GET /index.php" 200
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:25:03 +0000 "GET /index.php" 200
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:25:07 +0000 "GET /index.php" 404
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:25:07 +0000 "GET /index.php" 301
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:25:08 +0000 "GET /index.php" 404
skybookings-wordpress | [ip.hidden] - 25/Apr/2020:01:25:09 +0000 "GET /index.php" 20
```

**Comment by styssi** [comment]
Hi @gaisho,

just tested it on my system. Pressed F12 in my browser and also checked what is going on there. 
On my browser logs I see tons of files loading correctly and 2 css files with 404. The missing css is a current bug in the theme I am coding.
On my wordpress logs I see a 200, two 404 and a 302 for the same request. I guess the two 404 stand for the two css files that can't be found. So I would conclude the 404 is not a bug in @urre code. 
I don't know why the 302 is coming. Would be also really interested to find out about that.

Greetings
Tobi

**Comment by gaisho** [comment]
I suspect that it has something to do with SSL.  I'll keep digging.

**Comment by urre** [comment]
@gaisho Wordpress wise It's a standard Bedrock setup. I've used this on large sites, what plugins you use doesn't matter for the base setup.

Check if you are using pretty permalinks, (/page-name instead of /?p=12). If you have 404:s, it's often missing assets/other from your theme.

I'm running the base setup here and only one 200 for index.php for me. For example:
`myapp-wordpress | 172.26.0.2 -  25/Apr/2020:16:34:09 +0000 "GET /index.php" 200`
