### ISSUE TITLE
issue when trying to run create-cert.sh on Latest MacOS Catalina 10.15.4

### ISSUE THREAD

**Issue by fraubungle** [urre/wordpress-nginx-docker-compose#37]
Downloaded the repo, copied to folder, run brew install openssl but when doing so 

openssl version
LibreSSL 2.8.3

is the result i get

cli % ./create-cert.sh
Error Loading extension section SAN
4415454828:error:22FFF06D:X509 V3 routines:func(4095):invalid null value:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.100.4/libressl-2.8/crypto/x509v3/v3_utl.c:355:
4415454828:error:22FFF069:X509 V3 routines:func(4095):invalid extension string:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.100.4/libressl-2.8/crypto/x509v3/v3_conf.c:149:name=subjectAltName,section=DNS:
4415454828:error:22FFF080:X509 V3 routines:func(4095):error in extension:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.100.4/libressl-2.8/crypto/x509v3/v3_conf.c:100:name=subjectAltName, value=DNS:
plebeian@Marks-MacBook-Pro cli %

**Comment by fraubungle** [comment]
i might have managed to get past that with running

echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

but after doing that this next error pops

Error Loading extension section SAN
4639808960:error:2206D06D:X509 V3 routines:X509V3_parse_list:invalid null value:crypto/x509v3/v3_utl.c:353:
4639808960:error:22097069:X509 V3 routines:do_ext_nconf:invalid extension string:crypto/x509v3/v3_conf.c:93:name=subjectAltName,section=DNS:
4639808960:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=DNS:

**Comment by urre** [comment]
@fraubungle hm, interesting. I'm still on Mojave and it works fine. If you find a good solution, please let me know and create PR. I'll keep looking also.

**Comment by kovordaniy** [comment]
Had the same issue on Catalina.
Such error happens when DOMAIN variable has not been set in .env config.
Since .env.example file doesn't contain this variable probably makes initial set up a bit confusing.
Anyway it described in README file and works fine.
