### ISSUE TITLE
How to configure for multisite network?

### ISSUE THREAD

**Issue by HumidBrains** [urre/wordpress-nginx-docker-compose#38]
**Thanks for a great project @urre.**
**Do you have any experience on how to configure your project for WP Multisite?**

Roots claim Bedrock is multisite compatible and that you don't need to do anything is using subfolders as I do. https://roots.io/docs/bedrock/master/installation/#getting-started
Yet I cannot get this to work after having tried various tweaks.

Here is the Multisite setup I use for a well functioning standard project without Bedrock.
Here I've just adapted it for use in application.php instead of config.php. Any idea how I'd need to tweak things to make multisite work with your project structure?

Would be grateful for any help.

```php
/* application.php */
Config::define( 'WP_ALLOW_MULTISITE', true );
Config::define('MULTISITE', true);
Config::define('SUBDOMAIN_INSTALL', false);
Config::define('DOMAIN_CURRENT_SITE', 'mydomain');
Config::define('PATH_CURRENT_SITE', '/');
Config::define('SITE_ID_CURRENT_SITE', 1);
Config::define('BLOG_ID_CURRENT_SITE', 1);
Config::define('WP_ALLOW_REPAIR', true);
Config::define('WP_HOME','http://mydomain');
Config::define('WP_SITEURL','http://mydomain');
```
```ocaml
# .htaccess
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]
</IfModule>
```

**Comment by HumidBrains** [comment]
I sorted out my problem with not getting access to the database by stop making things unnecessarily complicated. It turned out that it doesn't work well writing all code at once in application.php and .htaccess. Instead, I needed to start with only setting multisite to true in application.php like so...

```php
Config::define('WP_ALLOW_MULTISITE', true);
```
Having done that the site allowed me to install WordPress from my chosen domain like for a single site.

Thereafter I logged in and went to wp-admin and the setup panel is in Tools > Network Setup

From there it's just a matter of following the instructions from WP admin by copying the code snippets generated and pasting them in application.php and .htaccess respectively.

They'll look something like this depending on the domain
```php
// application.php
Config::define('MULTISITE', true);
Config::define('SUBDOMAIN_INSTALL', false);
Config::define('DOMAIN_CURRENT_SITE', 'myapp.local');
Config::define('PATH_CURRENT_SITE', '/');
Config::define('SITE_ID_CURRENT_SITE', 1);
Config::define('BLOG_ID_CURRENT_SITE', 1);
```
```ocaml
# .htaccess
# BEGIN WordPress
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) wp/$2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ wp/$2 [L]
RewriteRule . index.php [L]

# END WordPress
```

Finally, I logged again and was good to go.

Hopefully, this can help someone else facing the same struggles I did.

**Comment by urre** [comment]
@HumidBrains thanks! Looks good. I'm planning on doing a docs site for this setup, Multisite is a good thing to get in there.

**Comment by HumidBrains** [comment]
Great @urre :) 
Today I noticed you need to install the roots/multisite-url-fixer plugin for the urls to work everywhere in WP admin. In the Bedrocks docs it says the plugin is not needed for subdirectories, but that's incorrect. https://roots.io/docs/bedrock/master/installation/#getting-started

```shell
composer require roots/multisite-url-fixer
```

**Comment by riccardobertolini** [comment]
> I sorted out my problem with not getting access to the database by stop making things unnecessarily complicated. It turned out that it doesn't work well writing all code at once in application.php and .htaccess. Instead, I needed to start with only setting multisite to true in application.php like so...
> 
> ```
> Config::define('WP_ALLOW_MULTISITE', true);
> ```
> 
> Having done that the site allowed me to install WordPress from my chosen domain like for a single site.
> 
> Thereafter I logged in and went to wp-admin and the setup panel is in Tools > Network Setup
> 
> From there it's just a matter of following the instructions from WP admin by copying the code snippets generated and pasting them in application.php and .htaccess respectively.
> 
> They'll look something like this depending on the domain
> 
> ```
> // application.php
> Config::define('MULTISITE', true);
> Config::define('SUBDOMAIN_INSTALL', false);
> Config::define('DOMAIN_CURRENT_SITE', 'myapp.local');
> Config::define('PATH_CURRENT_SITE', '/');
> Config::define('SITE_ID_CURRENT_SITE', 1);
> Config::define('BLOG_ID_CURRENT_SITE', 1);
> ```
> 
> ```ocaml
> # .htaccess
> # BEGIN WordPress
> RewriteEngine On
> RewriteBase /
> RewriteRule ^index\.php$ - [L]
> 
> # add a trailing slash to /wp-admin
> RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]
> 
> RewriteCond %{REQUEST_FILENAME} -f [OR]
> RewriteCond %{REQUEST_FILENAME} -d
> RewriteRule ^ - [L]
> RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) wp/$2 [L]
> RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ wp/$2 [L]
> RewriteRule . index.php [L]
> 
> # END WordPress
> ```
> 
> Finally, I logged again and was good to go.
> 
> Hopefully, this can help someone else facing the same struggles I did.

This was gold, thanks for sharing. Occam's razor hits again 👍
