### ISSUE TITLE
Cannot setup SSL on Chromium

### ISSUE THREAD

**Issue by zaifastafa** [urre/wordpress-nginx-docker-compose#42]
After following all the steps, I get a `.key` and `.crt` files in the `certs` folder, but when importing in `chromium` it says the private key is missing or invalid.

**Comment by urre** [comment]
@zaifastafa not sure how mean importing in Chromium? You can trust the certs using the CLI scripts. For Chrome/Safari. Only Firefox there is an instruction in the readme.

**Comment by zaifastafa** [comment]
@urre yes, but chromium is not imported by default through the script. So maybe if you can give instructions on setting up on chromium too.

**Comment by urre** [comment]
@zaifastafa did you manage to resolve this?

**Comment by zaifastafa** [comment]
@urre No unfortunately. I have moved onto another docker/wordpress setup. Thanks.
