### ISSUE TITLE
PHP-FPM

### ISSUE THREAD

**Issue by gerontius** [urre/wordpress-nginx-docker-compose#43]
I assume this is working but havent forked the repo but how are you getting nginx to serve php files without using a php-fpm image? I cant see any reference in the configs although the nginx config shows you are using fastcgi.

**Comment by urre** [comment]
@gerontius already using php-fpm. In the readme file I specify all the details. In the Dockerfile you see [what image I'm using](https://github.com/urre/wordpress-nginx-docker-compose-image)
