### ISSUE TITLE
Issues with trust-cert.sh under ArchLinux and Manjaro

### ISSUE THREAD

**Issue by Bensuperpc** [urre/wordpress-nginx-docker-compose#45]
I have issues with trust-cert.sh under ArchLinux and Manjaro:
Path "/usr/local/share/ca-certificates/" doesn't exist on these distro :/ 
I have this error : 
`cp: target '/usr/local/share/ca-certificates/' is not a directory`

`sudo update-ca-certificates` doesn't exist :/ 

For first issue, I did not find a solution.
I tried with : _/etc/ca-certificates/trust-source/anchors/_ but isn't working :/

I found a solution for second issue by replace `update-ca-certificates` with `trust extract-compat` The packages : _ca-certificates ca-certificates-mozilla ca-certificates-utils openssl_ are installed

Thank you, otherwise the rest works fine ^^

**Comment by urre** [comment]
@Bensuperpc did you manage to resolve this?

**Comment by urre** [comment]
@Bensuperpc I've switched to [mkcert](https://github.com/FiloSottile/mkcert) now so this script doesn't exist anymore.
