### ISSUE TITLE
Wordpress installation not working on initial setup

### ISSUE THREAD

**Issue by Chaoste** [urre/wordpress-nginx-docker-compose#46]
When following your instructions on Mac OS X, I've got a internal server error when opening the page.

The logs led me to this issue: https://github.com/roots/bedrock/issues/199

Actual fix for src/.env: Add the following three lines:
```
WP_ENV=development
WP_HOME=https://$DOMAIN
WP_SITEURL=https://$DOMAIN
```

**Comment by urre** [comment]
@Chaoste Yea, you need the regular WP ENV values in `./src/.env` also to run. Since this is a Bedrock project you can just do `docker-compose run composer create-project` and the `.src/env` will be created from the `./src/env-example`. 

I should clarify this in the readme. Thanks!
