### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by jswazzer** [urre/wordpress-nginx-docker-compose#47]
I am on Windows 10 and followed the instructions up to 🚀 Open https://myapp.local in your browser.  When I did that I received the message: "Error establishing a database connection".  

thanks, can't wait to try this out.

**Comment by mortensassi** [comment]
@jswazzer are you working on WSL? If so, try working on the wsl directory and not on `/mnt` - Works for me! If you need further help, hit me up :)

**Comment by urre** [comment]
@jswazzer what ENV settings are you using? thanks @mortensassi for helping out

**Comment by Zielgestalt** [comment]
Had the same problem. I forgot to edit the .env-example-file in ./src.
https://github.com/urre/wordpress-nginx-docker-compose#for-wordpress
