### ISSUE TITLE
Access denied for user 'root'@'172.18.0.2' (using password: YES)

### ISSUE THREAD

**Issue by xgrei** [urre/wordpress-nginx-docker-compose#50]
Thanks for this project, I got this error:

```
Access denied for user 'root'@'172.18.0.2' (using password: YES)
```

.env

```
IP=127.0.0.1
APP_NAME=wp
DOMAIN=example.com
DB_HOST=mysql
DB_NAME=wp
DB_ROOT_PASSWORD=password
DB_TABLE_PREFIX=wp_
```

how to fix this?

**Comment by urre** [comment]
@xgrei have you setup the project using `docker-compose run composer create-project`? then you should have an `./src/env` file with the correct `DB_USER`

**Comment by xgrei** [comment]
Thank you, I find `./src/.env`.
