### ISSUE TITLE
Nginx not passing requests further to Worpress

### ISSUE THREAD

**Issue by Chaoste** [urre/wordpress-nginx-docker-compose#51]
Hi urre,

thank you for your awesome work. I'm already using it right now for my third project! :) 

I am currently struggling with just accessing the page. Unfortunately, I don't fully understand the NGINX config which tries to find files in the nginx container with the first rule `location /`.

If I curl the server with `curl https://medals.local`, it returns "403" and logs `[error] 8#8: *11 directory index of "/var/www/html/" is forbidden`.

If I run `curl https://medals.local/composer.json`, it actually returns my `composer.json`.

Thus, I suspect it only tries to resolve my requests with the files in the nginx container and doesn't pass them further to the wordpress container. Do you have a clue what I could have mixed up with the config so this arises? And why at all do we need this first location block in the nginx config?

**nginx/default.conf**:
```
server {
    listen      80;
    listen [::]:80;
    server_name $domain;

    location / {
        rewrite ^ https://$host$request_uri? permanent;
    }
}

server {
    listen      443           ssl http2;
    listen [::]:443           ssl http2;
    server_name               $domain www.$domain;

    add_header                Strict-Transport-Security "max-age=31536000" always;

    ssl_session_cache         shared:SSL:20m;
    ssl_session_timeout       10m;

    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:!ADH:!AECDH:!MD5;";

    root /var/www/html;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ssl_certificate           /etc/certs/$domain.crt;
    ssl_certificate_key       /etc/certs/$domain.key;

    gzip on;
    gzip_http_version 1.0;
    gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_min_length 256;
  gzip_types
    text/css
    text/javascript
    text/xml
    text/plain
    text/x-component
    application/javascript
    application/json
    application/xml
    application/rss+xml
    font/truetype
    font/opentype
    application/vnd.ms-fontobject
    image/svg+xml;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

Greetings and thanks in advance,
Thomas

**Update:**
I was able to solve it by fixing my wrong defined "root" attribute which was missing the `/web` suffix. Still, I'd be interested in how this whole nginx config works. Why doesn't it just pass everything further to wordpress but holds those files separately in the nginx container?

**Comment by urre** [comment]
Hey @Chaoste,

It's a pretty standard nginx config. This is what the cURL command `curl -I -k https://myapp.local` returns:

```
HTTP/2 200 
server: nginx/1.17.6
date: Tue, 15 Sep 2020 19:47:53 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
x-powered-by: PHP/7.2.19
link: <https://myapp.local/index.php?rest_route=/>; rel="https://api.w.org/"
strict-transport-security: max-age=31536000
```

`/web` is used as the webroot in this repo. That is why the root should be set to `root /var/www/html/web;` in the nginx config. For Enhanced security with a separated web root. See  [Bedrock from roots](https://github.com/roots/bedrock)
