### ISSUE TITLE
wp-cli db commands not working, is it missing mysql-client?

### ISSUE THREAD

**Issue by aaronjpitts** [urre/wordpress-nginx-docker-compose#54]
When I log in to the container and run `wp db reset --yes --allow-root` it gives the error `/usr/bin/env: 'mysql': No such file or directory`, Is it missing the mysql-client?

Thanks in advance for your answer.

**Comment by aaronjpitts** [comment]
Got it working by running `apt-get update && apt-get dist-upgrade && apt-get install default-mysql-client` on the container. Is there a better way to have this installed as standard?

Thanks :)

**Comment by urre** [comment]
@aaronjpitts yes, thanks for noticing :) [Fixed now](https://github.com/urre/wordpress-nginx-docker-compose/blob/master/Dockerfile#L4)
