### ISSUE TITLE
How to remove SSL

### ISSUE THREAD

**Issue by ProdesignerAgency** [urre/wordpress-nginx-docker-compose#58]
Hello,
i have problems with removing SSL Certificate in localhost:3000 url.
How to make this work.
I have OSX Catalina.
Please help.
I have this error: ERR_SSL_PROTOCOL_ERROR

**Comment by urre** [comment]
@ProdesignerAgency 

to just run nginx on http://127.0.0.1:8080/ without using SSL you can use ↓

``
server {
    listen 80;
    server_name 127.0.0.1;

    root /var/www/html;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```
