### ISSUE TITLE
Nginx string interpolation seems to fail in docker-compose.yml

### ISSUE THREAD

**Issue by humblecoder** [urre/wordpress-nginx-docker-compose#61]
In the `docker-compose.yml` using `version:"3.6"`, there is a line of code as follows:

```
entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
```

`${DOMAIN}` is not appropriately substituted, and simply results in a `default.conf` nginx file that replaces all instance of `$domain` with blanks.

Hopefully I'm missing something obvious.  😣

**Comment by urre** [comment]
Hey, did did you create an .env file with the desired domain?

**Comment by humblecoder** [comment]
I did indeed.  My `.env` file looks like so:

```
IP=127.0.0.1
APP_NAME=wpdocker
DOMAIN=wpdocker.local
DB_HOST=mysql
DB_NAME=wpdocker
DB_ROOT_PASSWORD=password
DB_TABLE_PREFIX=wp_
```

When I `docker compose up` I receive the following error regarding nginx: `invalid number of arguments in "server_name" directive`.  When I output the string to debug it, `${DOMAIN}` is empty

All other values (e.g. `APP_NAME`) get pulled properly, but in that specific `entrypoint:` string, variable doesn't get pulled/parsed.  Is there, perhaps, something about the entrypoint string that .env vars don't get interpolated?

**Comment by urre** [comment]
Hm. Strange, haven't had any issues with this. What OS are you on?

**Comment by humblecoder** [comment]
Still running `MacOS Catalina 10.15.7` with `Docker Desktop v3.0.3(51017)`

**Comment by urre** [comment]
Interesting. I haven't heard any issues with this and I know many people that use it. But I'll do some investigating

**Comment by humblecoder** [comment]
Much appreciated.  Even performed a fresh pull and still the same thing.  Hoping I'm just missing something obvious.

**Comment by urre** [comment]
Hey! Can you try this PR I just put up: https://github.com/urre/wordpress-nginx-docker-compose/tree/feat/env-substitute-fix

I think this will work better in more setups. 

Do `docker-compose rm -v` first and then `docker-compose up` again

**Comment by humblecoder** [comment]
So, I pulled the PR, reset the container, forced a rebuild, and it still got the same error.  However, after adjusting the environment like so, it worked:

```
environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=".conf"
      - DOMAIN=${DOMAIN}
```

Now, I'm receiving a `PR_END_OF_FILE_ERROR` when attempting to connect over https, and some MySQL connection issues as well.  That said, the interpolation-specific issue can be considered resolved.  Much appreciated!

**Comment by urre** [comment]
thanks! Yes, I forgot the dashes in the `environment: ` and it should be `=` instead of `:`.

Investigating `PR_END_OF_FILE_ERROR` further

**Comment by urre** [comment]
Now this is fixed. I've also fixed the SSL errors and `PR_END_OF_FILE_ERROR`. 

Please test again. I'm merging this later

**Comment by humblecoder** [comment]
That fixed the SSL issue.  I'll take a closer look at the MySQL issue (and perhaps log a more coherent bug) if I get some time in the coming days.  Thanks!

**Comment by urre** [comment]
The PR is is now merged. 

Thanks!
