### ISSUE TITLE
(Question) Production

### ISSUE THREAD

**Issue by galakhov** [urre/wordpress-nginx-docker-compose#65]
Hi Urre, nice repo, thanks!

I've got a couple of questions regarding the best-practices for deployment to a VPS.
Besides [these](https://roots.io/docs/bedrock/master/deployment/) instructions, for production I still needed to include the `./src/vendor`, `./src/config` and the `./src/wp` directories in the final build.
You're ignoring them by default in your `.gitignore` files.

I needed to add these lines in the [Dockerfile](https://github.com/urre/wordpress-nginx-docker-compose-image) you're using before and after the `VOLUME` in order to run the WP:
```dockerfile
RUN set -ex; \
    mkdir -p -m775 /var/www/html/web/wp; \
    cp -ar /usr/src/wordpress/. /var/www/html/web/wp; \
    chmod -R 775 /var/www/html/web/wp

VOLUME /var/www/html

RUN mkdir -p -m775 /var/www/html/web/{vendor, config}
COPY src/vendor /var/www/html/web/vendor
COPY src/config /var/www/html/web/config
RUN chown -R www-data:www-data /var/www/html/web
# I mount all these three directories later with docker-compose.yml
```

Is this an appropriate way of doing things in production? Is there any specific production build routine for WP?
Do you maybe have some examples of a `Dockerfile` and/or `docker-compose.yml` (swarm stack?) files that you're using for production?

**Comment by urre** [comment]
Hey, sorry the late reply. Did you mean running this setup on a Docker-based VPS?

**Comment by galakhov** [comment]
> Hey, sorry the late reply. Did you mean running this setup on a Docker-based VPS?

Hi Urre, yeah, that's exactly what I meant. I was asking for a production-ready `docker-compose.yml` file.

**Comment by urre** [comment]
Ok gotcha! No, not yet. I haven't used exaclty this in production yet, only locally. But I have plans to do so. Yes, I'm ignoring them because its the default way in Bedrock. 

Your solution will work fine!
