### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by DannyMoerkerke** [urre/wordpress-nginx-docker-compose#67]
When I run ` curl -I -k https://myapp.local` I get `curl: (7) Failed to connect to myapp.local port 443: Connection refused`.
I also notice `src/.env` is not generated.
When I visit `http://myapp.local` (no https) I get the Nginx welcome page only.

I probably messed it up myself but I don't know what I did wrong. I tried with the Nginx config unchanged and the one in the readme but neither work.

**Comment by urre** [comment]
Hey, did you install using `docker-compose run composer create-project`? with that command a `./src/.env` should be created from `./src/env-example`

**Comment by DannyMoerkerke** [comment]
Yes I did and I see now what goes wrong:
```
php -r "copy('.env.example', '.env');"
Warning: copy(.env.example): Failed to open stream: No such file or directory in Command line code on line 1
```

So it's looking for `.env.example` instead of `.env-example`.
It creates `.env` now but still doesn't work so I'll start from scratch first to see if it works.

I'm a bit confused by step 2 though.
Shouldn't `WP_HOME` point to `https://myapp.local`?
And why the simple Nginx config?
I assume I should add `127.0.0.1 myapp.local` to `/etc/hosts`.

I'll try again and let you know, thanks!

**Comment by urre** [comment]
Oh, sorry. Thanks for finding that. It should be `./src/.env.example`. I'm pushing a fix for it now.

For the next step. It's either step 1) or 2), not both. If you want to use a local domain with HTTPS  use 1). If you want a simpler approach on localhost without HTTPS, use step 2)

For step 1) `WP_HOME='https://myapp.local'` is already added in the `./src/env.example`

**Comment by urre** [comment]
Made a clarification in the readme about 1) and 2)

Let me know if you have more questions!

**Comment by DannyMoerkerke** [comment]
Thanks, yes I figured out that it should either be 1 or 2 but it wasn't obvious from the readme at first.
I couldn't get Chrome to accept the certificate yet, I will have another look tomorrow, thanks!

**Comment by urre** [comment]
Great. I'm using [mkcert](https://github.com/FiloSottile/mkcert) so should be trusted in all browsers. Use: `cd cli && ./create-cert.sh`

**Comment by natac13** [comment]
Not trying to hi-jack this issue and I will gladly create a new one if requested. However, I have not been successful at getting the certificate working. 
Were you successful @DannyMoerkerke?

I have got the certificate created and the browser does see it but still not SSL.
![issue-777](https://user-images.githubusercontent.com/10660283/110153792-804ac800-7db1-11eb-8ef7-7ba078b0d703.png)

**Comment by urre** [comment]
@DannyMoerkerke did you get it working now?

**Comment by DannyMoerkerke** [comment]
Yes! And I just figured out why it didn't work.

When running `./create-cert.sh` I got the note:
```
Note: the local CA is not installed in the system trust store.
Note: the local CA is not installed in the Firefox trust store.
Run "mkcert -install" for certificates to be trusted automatically 
```

In `create-cert.sh`, when I change:
```
mkcert "${DOMAIN}"
```
to
```
mkcert -install "${DOMAIN}"
```
it works on MacOS, although I don't know if it's related to MacOS.

**Comment by urre** [comment]
AH, interesting. What version of macOS do you use?

This is what I get when running `./create-cert.sh`

```
❯ ./create-cert.sh 
Using the local CA at "/Users/urbansanden/Library/Application Support/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "myapp.local"

The certificate is at "./myapp.local.pem" and the key at "./myapp.local-key.pem" ✅
```

**Comment by urre** [comment]
you are right @DannyMoerkerke I just added `-install` in the cli script. Thanks!
