### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by deviland** [urre/wordpress-nginx-docker-compose#68]
Hi @urre thanks for creating this repo.

I have run the steps and have ran `docker compose up -d` and everything seems fine but I do get the above error
from Wordpress when I attempt to load the admin.

I also see that the composer container is not running should it be?

thanks in advance for your help

I include the env file below
```
IP=127.0.0.1
APP_NAME=themetest
DOMAIN=themetest.local
DB_HOST=mysql
DB_NAME=themetest
DB_ROOT_PASSWORD=password
DB_TABLE_PREFIX=wp_
```

**Comment by urre** [comment]
Hi, what error did you get in wp-admin?

**Comment by deviland** [comment]
HI the same error, I'm going through the process again to see if I've made a mistake somewhere

**Comment by deviland** [comment]
Hey @urre I reran the steps in the guide and got the same result have I got something wrong in the above `.env` file? this is the only place I have edited

**Comment by urre** [comment]
did you install using `docker-compose run composer create-project`?

**Comment by deviland** [comment]
yes this works and I can see the requests coming through to nginx

**Comment by deviland** [comment]
![Uploading Screenshot 2021-03-04 at 15.38.31.png…]()

**Comment by deviland** [comment]
```
themetest-wordpress | 192.168.0.7 -  04/Mar/2021:15:40:08 +0000 "GET /index.php" 500
themetest-nginx | 192.168.0.1 - - [04/Mar/2021:15:40:08 +0000] "GET / HTTP/2.0" 500 2609 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
themetest-wordpress | 192.168.0.7 -  04/Mar/2021:15:40:13 +0000 "GET /index.php" 500
themetest-nginx | 192.168.0.1 - - [04/Mar/2021:15:40:13 +0000] "GET /wp-admin HTTP/2.0" 500 2609 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
themetest-mailhog | [APIv1] KEEPALIVE /api/v1/events
```

**Comment by deviland** [comment]
think I'm getting closer the logs from `docker compose run compose create-project` 

I'm getting 

```
Creating wordpress-nginx-docker-compose-master_composer_run ... done
> php -r "copy('.env.example', '.env');"

Warning: copy(.env.example): Failed to open stream: No such file or directory in Command line code on line 1
```

**Comment by urre** [comment]
Right. I actually fixed this in a commit yesterday. There was a typo in the example env and no .env got created.

But this is fixed now, can you please do a new pull

**Comment by urre** [comment]
Sorry for this. But it's now called .env.example and not .env-examole

**Comment by deviland** [comment]
hey no need to say sorry you're repo will save me hours of work 👍 

Glad I can help by feeding back

should I be editing the `/.env.example` or the `/src/.env.example`?

**Comment by deviland** [comment]
I have the latest code now 👍

**Comment by deviland** [comment]
This is my output now

```
docker-compose run composer create-project
WARNING: The APP_NAME variable is not set. Defaulting to a blank string.
WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The DB_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The DB_HOST variable is not set. Defaulting to a blank string.
```

**Comment by deviland** [comment]
sorry to keep coming back I edited both `/.env.example` and `/src/env.example` and still hd the above output. I'm sure this is me missing something

**Comment by urre** [comment]
You should edit both env example files before you install. Both in the root and in `./src`. The file in the root is called `./env-example` but in the src it is called `./src/.env.example`

Read more in the Readme here under under [Instructions](https://github.com/urre/wordpress-nginx-docker-compose#instructions)

The warnings above you can ignore for now.

If you run `docker-compose up -d` and head over to [https://myapp.local/wp/wp-admin](https://myapp.local/wp/wp-admin) now it should work fine. You you should see this screen:

![](https://res.cloudinary.com/urre/image/upload/v1614933755/screenshots/mrp3txkeitcb8tygdhmo.jpg)

**Comment by deviland** [comment]
![Screenshot 2021-03-05 at 10 12 50](https://user-images.githubusercontent.com/244744/110101406-643c2c00-7d9b-11eb-8537-a07a6dffb94c.png)

she's a thing of beauty!

Thanks for your help, the eventual fix that worked was using `docker image rm` and starting gain following your above advice.

**Comment by urre** [comment]
Great! Thanks for your feedback
