### ISSUE TITLE
wp-cli errors

### ISSUE THREAD

**Issue by v3nt** [urre/wordpress-nginx-docker-compose#7]
```
docker exec -it myapp-wordpress bash
````

````
/var/www/html# wp search-replace https://olddomain.com https://myapp.local --allow-root
````

returns this error -

```
Error: The site you have requested is not installed.
Run `wp core install` to create database tables.
```

And running -

`/var/www/html# wp`

`Error: YIKES! It looks like you're running this as root...`

**Comment by urre** [comment]
@v3nt have you installed WordPress using Composer first? The wp-cli command requires a WP installation

```cd src
composer install
```

**Comment by urre** [comment]
@v3nt about the permissions for wp-cli you'll have to add `--allow-root` after the commands

**Comment by alevgal** [comment]
I have the same problem, and when I'm using wp acorn --allow-root flag is not supported. So I executed it with www-data user `docker exec -it -u www-data  myapp-wordpress bash`
