### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by GarikHG** [urre/wordpress-nginx-docker-compose#74]
Sage-10 have Fatal error: Uncaught Error

Fatal error: Uncaught Error: Call to undefined method Dotenv\Repository\RepositoryBuilder::createWithDefaultAdapters() in /var/www/html/web/app/themes/sage-10/vendor/illuminate/support/Env.php:55 Stack trace: 
#0 /var/www/html/web/app/themes/sage-10/vendor/illuminate/support/Env.php(76): Illuminate\Support\Env::getRepository() #1 /var/www/html/web/app/themes/sage-10/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(1067): Illuminate\Support\Env::get('APP_CONFIG_CACH...') 
#2 /var/www/html/web/app/themes/sage-10/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(1015): Illuminate\Foundation\Application->normalizeCachePath('APP_CONFIG_CACH...', 'cache/config.ph...') 
#3 /var/www/html/web/app/themes/sage-10/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/LoadConfiguration.php(24): Illuminate\Foundation\Application->getCachedConfigPath() #4 /var/www/html/web/app/themes/sage-10/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(237): Roots\Acorn\Bootstrap\LoadConfiguration->bootstrap(Object(Roots\Acorn in /var/www/html/web/app/themes/sage-10/vendor/illuminate/support/Env.php on line 55

**Comment by urre** [comment]
@GarikHG  This repo doesn't ship with Sage so not considering this an issue.
