### ISSUE TITLE
Question: Use this repo without bedrock or composer

### ISSUE THREAD

**Issue by azeem-khan** [urre/wordpress-nginx-docker-compose#76]
Thanks Urre for all you're work on this. I use this repo on a daily basis now!

I wanted to ask if you could upload some instructions or give the options to develop using this repo without bedrock or composer.

Reason for this is some basic hosts when deploying do not really work with bedrock / have composer installed.

I did try messing around and deleting composer but I just kept running into issues.

Any help or direction would be much appreciated!

**Comment by urre** [comment]
Hey! Nice to hear.

Sure, it's easy.

1. Remove `composer.json`, `composer.lock` and the `vendor` folder. Also empty the `web` folder
2. If not using SSL. Remove ` - '443:443'` from `docker-compose.yml`
3. You can also use a simple nginx config like this:

```server {
    listen 80;

    root /var/www/html/web/wp;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```
3. Start `docker compose up`
3. In a separate tab - download a standard WordPress installation using 

```
docker exec -it myapp-wordpress bash
```

and 

```
wp core download --allow-root
```

4. Visit http://127.0.0.1/
