### ISSUE TITLE
Existing database

### ISSUE THREAD

**Issue by huraji** [urre/wordpress-nginx-docker-compose#78]
Can you make an example with and existing database?

**Comment by urre** [comment]
Do the installation first, that will create an empty database.

```
docker exec -it myapp-wordpress bash
```

Import an existing database using

```
wp db import my-database.sql --allow-root
```

Or import it with ex Sequel Pro

Replace URLs if needed:
```
wp search-replace https://olddomain.com https://newdomain.com --allow-root
```
