### ISSUE TITLE
Cannot run composer in wordpress container

### ISSUE THREAD

**Issue by huraji** [urre/wordpress-nginx-docker-compose#80]
When I am trying to run something like `composer require` I get

`bash: composer: command not found`

Is it intended or am I doing something wrong?

**Comment by huraji** [comment]
I had just the wrong approach. For future wanderers, just require your plugins from the `src/` directory. They will be mounted with the volume.

**Comment by urre** [comment]
You can run ex `docker compose run composer update` from the root folder.
