### ISSUE TITLE
Filesystem permission

### ISSUE THREAD

**Issue by hsehszroc** [urre/wordpress-nginx-docker-compose#81]
I am getting an issue with the filesystem permission when trying to add a new plugin.

**_WordPress needs to access your web server. Please enter your FTP credentials._**

Solved it with the below code added on "**/src/config/application.php**".
```PHP
/**
 * Filesystem access.
 */
Config::define('FS_METHOD', 'direct');
```

Anybody having the same issue?
![Screenshot 2021-11-02 at 11-04-47 Add Plugins ‹ Docker Site — WordPress](https://user-images.githubusercontent.com/48177731/139790917-b2c0e7ea-32ff-49b2-b5b4-3f3ec970cb91.png)

**Comment by hsehszroc** [comment]
Using:

- Docker
  - version 20.10.8
  - build 3967b7d 
- Windows 10 Pro
  - version 20H2
  - OS Build 19042.1288.

**Comment by urre** [comment]
Hey @hsehszroc! Updating plugins are meant to be done with Composer in this setup. 

Like this example to install ACF

```
docker compose run composer require wpackagist-plugin/advanced-custom-fields
```

But there is a section on updating plugins [in admin here in the readme](https://github.com/urre/wordpress-nginx-docker-compose#update-plugins-and-themes-from-wp-admin)

**Comment by hsehszroc** [comment]
Forgot about composer and info on readme.

Thanks for the update.

**Comment by urre** [comment]
Cool. Let me know if you have more issues
