### ISSUE TITLE
Plugin Installation Issues

### ISSUE THREAD

**Issue by RobHowdle** [urre/wordpress-nginx-docker-compose#83]
Hello! 

I love this repo, it's given me everything I need to easily create my websites so firstly thank you for your hard work. I have studied the readme and checked over various other issues that have been opened to try to solve my problems but there are a couple that I'm struggling with. I'll open them as separate issues to avoid confusion.

I'm currently running Ubuntu 20 as my OS, with Docker installed. I am still fairly new to docker but I've navigated into the app/ plugins folder and tried to run
`wp plugin list`
and I am greeted with the error of 
Error: Your PHP installation appears to be missing the MySQL extension which is required by WordPress.
I did some research and tried various things, I did a wp --info to make sure it was installed and here is my output
```
S:	Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.27
php.ini used:	/etc/php/7.4/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/rob/Desktop/Sites/ma/src/web/app/plugins
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	/home/rob/Desktop/Sites/ma/src/wp-cli.yml
WP-CLI version:	2.5.0
```

I did downgrade my php from 8 just encase that was the issue but that didn't work. Could you please suggest where I am going wrong? I did try to add the flags to allow plugins to be installed from the dashboard however even with restarting the container, this didn't work. It still asks for the FTP details.

Thanks
Rob

**Comment by RobHowdle** [comment]
@urre Is there any chance of getting a response to this please?

**Comment by RobHowdle** [comment]
Found the issue. I was being blind. The readme does say about wp-cli but when I googled it, nothing came up to specifically say how to open a bash terminal, I was just using shell which didn't work.

`docker exec -it myapp-wordpress bash`

changing myapp to whatever you've named it - just for reference :)

**Comment by urre** [comment]
@RobHowdle great! Yea, I could maybe be more clear about this in the readme. Thanks!

**Comment by RobHowdle** [comment]
No problem! My own fault for not 100% reading through the readme ha, you do quite clearly state it. It could be an idea perhaps to maybe have some FAQs? Scrolling through some of the issues and things people have posts, even in the WIKI section you could have FAQs. I'd be happy to help with this also :)
