### ISSUE TITLE
Update vlucas/phpdotenv to ^5.4

### ISSUE THREAD

**Issue by basvandertogt** [urre/wordpress-nginx-docker-compose#90]
Is it possible to update vlucas/phpdotenv to the latest version 5.4.1 ?
The config files should be updated then as well.

**Comment by urre** [comment]
It should be possible. I'll check

**Comment by urre** [comment]
It seems to work fine. Check https://github.com/urre/wordpress-nginx-docker-compose/pull/91

**Comment by urre** [comment]
PR merged
