### ISSUE TITLE
Performance on M1 Apple MacBook Pro

### ISSUE THREAD

**Issue by pixeline** [urre/wordpress-nginx-docker-compose#93]
Hello!
Thank you very much for providing this setup. I notice it is very slow on my 2021 Macbook Pro and suspect it may be because of the cpu: Apple Silicon M1.
I googled a bit and read [this](https://www.proudcommerce.com/devops/docker-performance-on-apple-macbook-pro-with-m1-max-processor-status-and-tips) which seems to confirm it.

Anyone else running into this issue?

**Comment by urre** [comment]
Very interesting, I just switched to a new M1 Mac here also. Haven't tested it fully yet on everything, but will check.
