### ISSUE TITLE
WordPress & PHP versions

### ISSUE THREAD

**Issue by wavehamza** [urre/wordpress-nginx-docker-compose#94]
Hello @urre,

Would love to know if we can customize the docker image to be dynamic (support multiple PHP version example latest 8.1) and latest version of WordPress (if we don't specify the version 6.0.1 for example).

Best regards.
H/

**Comment by urre** [comment]
Hey, 

Sure, In the [Dockerfile](https://github.com/urre/wordpress-nginx-docker-compose/blob/master/Dockerfile#L1) I use this image: https://github.com/urre/wordpress-nginx-docker-compose-image

You can fork that if you want
