### ISSUE TITLE
Unable to update/install theme or plugin

### ISSUE THREAD

**Issue by mkenacnibuk** [urre/wordpress-nginx-docker-compose#96]
I'm able to successfully run given containers and open website locally - **many thanks you put it all together.**

But then problems comming - plugins, themes not able to install or update.
![image](https://user-images.githubusercontent.com/17276604/186531274-23c331ee-9d5e-4104-9d22-c5868bbb0b18.png)

Of course I instinctively checked docker-compose.yml for wordress service focused on volumes:
![image](https://user-images.githubusercontent.com/17276604/186531192-4a79e55f-7bd5-4632-a7ab-e2fe6c007d7e.png)

[How to Fix Could Not Create Directory Error in WordPress](https://www.cloudways.com/blog/wordpress-installation-failed-could-not-create-directory/)  seems to be clear and easy fix, so in a while I strictly (775 instead of only 755, but tied 755 also) made sure the file structure content permissions are ok, so using terminal CLI:
```
docker compose down
whoami --> os-user
cd wordpress-nginx-docker-compose/
chown -R os-user::os-user src
cd src
chmod -R 775 web
docker compose up -d
```

On background checked file permissions' settings ( 775, I know 755 should be enough ) had been successfully reflected on local dir content, mainly src/web/wp-content/{plugins|themes} **but situation is still the same and I'm not able to overcome unability to update/install theme/plugin**
```
os-user@os-user-nb:~/code/gh/wordpress-nginx-docker-compose/src$ ll web/wp/wp-content/
total 20
drwxrwxr-x  4 os-user os-user 4096 apr  5 21:12 ./
drwxrwxr-x  5 os-user os-user 4096 apr  5 21:12 ../
-rwxrwxr-x  1 os-user os-user   28 apr  5 21:12 index.php*
drwxrwxr-x  2 os-user os-user 4096 apr  5 21:12 plugins/
drwxrwxr-x 14 os-user os-user 4096 apr  5 21:12 themes/

```

I found another way how to see on that in worpress using left sidebar Tools --> Info all permissions are [**Not writable**] 
![image](https://user-images.githubusercontent.com/17276604/186530719-c432e4f6-06dc-4879-b984-e08f3d21a5e8.png)

This is just my 2nd day on dockerized wordpress, but I'm not able to fidn out what else I could do. Don't you have some tip/trick please?

**Comment by urre** [comment]
Hi @mkenacnibuk,

This setup isn't meant to allow plugin installs etc from wp-admin on production. The primary way to install and update plugins is with Composer. 

But it's easy to change if you want this.

in `./src/config/environments/production.php` (or desired env) set

```yml
// Enable plugin and theme updates and installation from the admin
Config::define('DISALLOW_FILE_MODS', false);
```

**Comment by mkenacnibuk** [comment]
Hi @urre , after >12yrs on java decided to clear mind/brain/myself and try to make some simple web site for friend but told myself "hey don't wast time like you were doing it during study times using lamp/wamp/xamp/... and look for dockerized wordpress". i've found some youtube channels and one was about your nicely prepared skeleton. Based on your response I've send wife with kids to town today and spend 4hrs on youtube focused on composer, packagist, wpackagist, bedrock,...

pffuuu very interested, but now I know what you mean. thanks a lot ;-)
