### ISSUE TITLE
PHP 8.1 update for Sage10

### ISSUE THREAD

**Issue by RichForever** [urre/wordpress-nginx-docker-compose#98]
Is there any chance to update php version to 8.1? When I’m trying to run sage theme I have a error regarding php version.

cheers

**Comment by urre** [comment]
Maybe, my experience is that 8.0 has worked better than 8.1x but will test again

**Comment by basvandertogt** [comment]
Any news on this? It would be nice to support PHP 8.1 :-)

**Comment by basvandertogt** [comment]
It would be nice to support PHP 8.2 from now on.

**Comment by urre** [comment]
Yea, started testing that yesterday actually. Will let you know

**Comment by urre** [comment]
Fixed now!

**Comment by basvandertogt** [comment]
Is it possible to make a v1.5.0 for PHP 8.2?
urre/wordpress-nginx-docker-compose-image:1.5.0
